### ISSUE TITLE
Windows warning about gdrv.sys when i try to patch

### ISSUE THREAD

**Issue by vico93** [valinet/NewOutlookPatcher#5]
![image](https://github.com/valinet/NewOutlookPatcher/assets/3485505/eb5b6d00-0cc7-4cf0-83ec-da30bba085b7)

Sorry the fact the dialogs are in Brazilian Portuguese, but when i try to click on Patch and accept the UAC dialog, this warning shows up and when Outlook reopens the changes wasnt applied.

Is this expected?

**Comment by valinet** [comment]
Probably. I tested this on Windows 10 only at the moment. The `gdrv.sys` driver is known to be poorly written - it allows for arbitrary read/write in kernel memory. I use it here in order to alter kernel's memory and briefly disable driver signature enforcement, so as to load my custom unsigned driver which copies the patcher to `WindowsApps`, where Outlook is installed. Once I do the copy, both my driver and `gdrv.sys` get unloaded from the kernel. If one finds another method to do the file copying, I will surely drop this.

What does the dialog say? Are you able to proceed? Maybe try disabling SecureBoot, and then Windows will let you continue. Once the patcher copies the file there, you can enable Secure Boot back.

**Comment by valinet** [comment]
Okay, so apparently they revoked the cert of the GIGABYTE driver in Windows 11 22H2. Oh, well...

**Comment by valinet** [comment]
Should be fixed, now using another driver to temporarily disable DSE. Try version 2024.03.15.03.

**Comment by valinet** [comment]
Try new version, revamped injection architecture: https://github.com/valinet/NewOutlookPatcher/releases/tag/2024.06.24.01
